version: "3.8"
services:
  mysql:
    image: mysql:5.7.44
    container_name: mysql5744
    ports:
      - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: redis:7.2.4
    container_name: redis724
    env_file:
      - .env
  dog_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog_app
    command: sh -c "./wait-for.sh mysql5744:3306 redis724:6379 -- ./dog_app ./conf/config.yaml"
    ports:
      - "9001:9001"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
