name: "dog"
mode: "dev"
port: 9001
log:
  level: "debug"
  filename: ".web.log"
  max_size: 200
  max_age: 30
  max_backups: 5
mysql:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
redis:
  host: ${REDIS_ADDR}
  port: ${REDIS_PORT}
  password: ""
  db: 0
  pool_size: 100
ethclient:
  url: ${ETH_CLIENT_URL}